services:
  postgres:
    image: postgres:13
    container_name: users_service_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: cubi12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - users_service_network

  rabbitmq:
    image: rabbitmq:3-management 
    container_name: rabbitmq
    ports:
      - "5672:5672"       
      - "15672:15672"    
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


volumes:
  postgres_data:

networks:
  users_service_network:
    driver: bridge
