version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: users_service_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: cubi12
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - users_service_network

volumes:
  postgres_data:

networks:
  users_service_network:
    driver: bridge
